### ISSUE TITLE
`description` don't always exist

### ISSUE THREAD

**Issue by molanp** [FragLand/minestat#200]
### Expected Behavior
* Normal output information

### Actual Behavior/Symptoms
* raise `KeyError`

### How to Reproduce Behavior/Symptoms
* When mc server does not return motd.

### MineStat Version
* 2.6.1

### Programming Language and Compiler/Interpreter Version
* Python 3.10.12

### Operating System
* Ubuntu

### Output/Screenshot(s)

```shell
root@localhost:~# python -V
Python 3.10.12
root@localhost:~# python test/error.py
MineStat Version 2.6.1
Line  794 Test, payload_obj is:  {'version': {'name': 'Spigot 1.20.1', 'protocol': 763}, 'players': {'max': 2023, 'online': 0}}
Traceback (most recent call last):
  File "/root/test/error.py", line 5, in <module>
    ms = data.MineStat("119.188.240.80", 54076)
  File "/root/test/data.py", line 317, in __init__
    self.json_query()
  File "/root/test/data.py", line 776, in json_query
    return self.__parse_json_payload(payload_raw)
  File "/root/test/data.py", line 797, in __parse_json_payload
    if isinstance(payload_obj["description"], str):
KeyError: 'description'
root@localhost:~#
```

**Comment by mindsolve** [comment]
Hi molanp,

Thanks for your bug report!

That was fun - I always assumed that the MOTD is mandatory. But leaving the motd config option empty (setting it to an empty string) in Spigot results in the element `description` completely missing from the server list ping JSON.
Since the original Minecraft client handles this gracefully, we should also probably do this.
