### ISSUE TITLE
1.16.3 Minecraft Server is shown as offline

### ISSUE THREAD

**Issue by rawora-rg** [FragLand/minestat#46]
### Expected behavior
Since the Minecraft Server is online, the ping should work and it should be displayed as online.
It used to work perfectly before. Is it because of the 1.16.3 ?
I checked this with other APIs (like [mcsrvstat.eu](https://mcsrvstat.us/server/netheranarchy.org)) and they do have it displayed as online.

### Actual behavior/symptoms
`#isServerUp()` returns false

### Steps to reproduce behavior/symptoms
```
MineStat ms = new MineStat("netheranarchy.org", 25565);
System.out.println(ms.isServerUp());
``` 
will return `false`.

### MineStat version
[Current Version (Latest commit 8 May)](https://github.com/FragLand/minestat/blob/master/Java/me/dilley/MineStat.java)

### Programming language and compiler/interpreter version
Java

### Operating system
Running on Ubuntu

**Comment by rawora-rg** [comment]
Since `MineStat ms = new MineStat("mc.hypixel.net", 25565);` works and shows the server as online, I'm not sure if this is a mistake on my end.

I would be grateful for any help, as to why this does not seem to work for my hostname.
The IP I use to connect to my minecraft server is `netheranarchy.org` and the default port (25565)

**Comment by ldilley** [comment]
Greetings, @rawora-rg.

I am unable to resolve `netheranarchy.org` to test, but I'm sure the query will work with the PHP or Ruby implementations of MineStat if you try those. This is a result of the Java implementation of MineStat lacking support for SLP (Server List Ping) 1.7. Have a look at the support matrix in issue #43. This is also related to issue #21. Unfortunately, I do not have an ETA for a Java fix due to other interests and obligations. As a workaround, perhaps you could use the other supported languages in the interim. There may additionally be other Java programs out there with support for the SLP 1.7 JSON query type.

**Comment by rawora-rg** [comment]
Hello @ldilley and thanks for your explanation.

For now I'm making use of a different API with a JSON response 

So there is no hurry for me to fix it :)

Regards
